#!/usr/bin/env python3
"""Regenerate the data block inside dce-torsion.html from the scan/frequency outputs in samples/.

    python3 tools/dce_data.py
"""
import json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from gaussian_modes import parse as modes
from gaussian_scan import parse as scan

def textscan(path):
    return [[float(a), float(b)] for a, b in (l.split() for l in open(path) if l.strip() and not l.startswith('#'))]

S = os.path.join(ROOT, 'samples')
# Scans: text files of "phi  E_hartree" (add a Gaussian scan log with scan(path,[1,2,3,4]) when the APFD gas-phase run is done)
apfd = scan(os.path.join(S, 'dce-apfd-scan.log'), [1, 2, 3, 4])
SCANS = [
    {'name': 'APFD/6-311+G(2d,p), gas phase', 'color': '#3366cc', 'pts': [[p['phi'], p['E']] for p in apfd]},
    # {'name': 'B3LYP, gas phase', 'color': '#cc6633', 'pts': textscan(os.path.join(S, 'dce-b3lyp-scan.txt'))},
]
SCAN_GEOMS = [{'phi': p['phi'], 'xyz': p['xyz']} for p in apfd]
def freq(tag):
    m = modes(os.path.join(S, f'dce-apfd-{tag}.log'), tag)
    return {'xyz': m[0]['xyz'], 'modes': [{'freq': round(x['freq'], 1), 'ir': round(x['ir'], 2), 'raman': round(x['raman'], 2), 'disp': x['disp']} for x in m]}
FREQ = {'anti': freq('anti'), 'gauche': freq('gauche')}

J = lambda o: json.dumps(o, separators=(',', ':'))
block = ("// ---- DATA START (generated by tools/dce_data.py from samples/dce-*; do not edit by hand)\n"
         f"const SCANS = {J(SCANS)};\n"
         f"const SCAN_GEOMS = {J(SCAN_GEOMS)};\n"
         f"const FREQ = {J(FREQ)};\n"
         "// ---- DATA END\n")
page = os.path.join(ROOT, 'dce-torsion.html')
s = open(page).read()
a = s.index('// ---- DATA START'); b = s.index('// ---- DATA END\n') + len('// ---- DATA END\n')
open(page, 'w').write(s[:a] + block + s[b:])
print(f'wrote {len(block)} bytes of data into dce-torsion.html')
